#! /bin/sh
################################################################################
#
# Copyright (c) 2017 Philippe Merle, Inria
#
# This file is part of CloudLex.
#
# CloudLex is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CloudLex is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CloudLex.  If not, see <http://www.gnu.org/licenses/>.
#
# Contributors:
# - Philippe Merle <philippe.merle@inria.fr>
#
################################################################################

# Iterate over all the cloud providers.
for provider in '1and1 Cloud Server' 'Apache CloudStack' 'Cloud Foundry' 'DigitalOcean' 'Docker Engine' 'Google Cloud Platform' 'Heroku' 'IBM Bluemix' 'Kubernetes' 'Microsoft Azure' 'OCCI' 'OpenStack' 'Oracle Cloud' 'OVH' 'Rackspace' 'VMware'
# TODO: Add other cloud providers to the previous list.
do
  echo "############################################################"
  echo "#"
  echo "# Running CloudLex on $provider"
  echo "#"
  echo "############################################################"
  cd "$provider"
  sh runAll.sh
  cd ..
done

echo "############################################################"
echo "#"
echo "# Running CloudLex on all Cloud REST API Datasets"
echo "#"
echo "############################################################"

export PYTHONPATH=../toolchain:$PYTHONPATH

CLOUDLEX_TOOLCHAIN_DIR=../toolchain/cloudlex

ALL_DATASETS="*/datasets/DatasetURIs.csv"

echo All Cloud REST API Datasets generated by CloudLex are:
wc ${ALL_DATASETS}

echo Generating CloudLex statistics for all Cloud REST APIs...
python ${CLOUDLEX_TOOLCHAIN_DIR}/statistics.py ${ALL_DATASETS} > results/statistics.log

echo Generating the CloudLex Lexicon CSV for all Cloud REST APIs...
python ${CLOUDLEX_TOOLCHAIN_DIR}/lexicon_csv.py ${ALL_DATASETS} > results/global_lexicon.csv

echo Generating the CloudLex Lexicon Tag Cloud for all Cloud REST APIs...
python ${CLOUDLEX_TOOLCHAIN_DIR}/lexicon_tag_cloud.py results/global_lexicon_tag_cloud.png ${ALL_DATASETS}

# TODO: Add other global computations on all the Cloud REST APIs.
